language: python
python:
 - '3.5'
 - '3.6'
 - '3.7'
 - '3.8'
before_install:
 - pip install git+https://github.com/sopel-irc/sopel.git
install:
- pip install -e .
- pip install -r dev-requirements.txt
script:
- flake8 --ignore=E501,E722,F401,F403 ./
deploy:
  provider: pypi
  user: rustybower
  password:
    secure: iGlwaqTrn9eBsgElyyUsBkakkaff2a7hJ5UuNl+HXvDE1rvi/b3ji+nypIKTV/PbAUM9wl730M4lwaZ5XwYuIvNUdoe5e7aKZCDJnro4U3OL/LuHmV7elM+eJOqYZsGxJj0xhOjTeYQbYFskn+PqHiMIo/WlTm7PkMyIgjJC9ghdv08mwQu0W69Kkvp/hlLXBEOeqOoIVreoyr1byCu3zQpA7CsMtz0ZbAfeMitohrA3CGsbDq99PO4mRHXWrP8gibUmtjmnglD/oq5PfVaKgTRY5zN0/79CwfoHfdBYz8DK7LZXuG0clmesHuLtaNddXfUKqDa21+SA50avzDKC+TQ3xI8F3USnHMXcTDUiFKGVgNtporGMRSe9oqsTc+tw8mbmqqf3s1Ykx1Y3SBj0yuqrDiiUfj6o8UpDBd3UyqbIzFalmvqKQsMMwmcfZ1uo2u2PT+CrMVMPbJr8oVMqSJQl+C9ch81hpB4HfvkA8833uLJivd9m+Ghbb/Z7mb82TrJlTh8yGiNtBw4ECgN6iXWIHV3sx7xL3qoFHpXcmZWewzekx3FZw42Ff9YCHkc5MU9CXzIxla/5eVcIvNchH3exIlVy4Hko1eSyeLtKoCVsuzwpndhshkc2/5eqhMboNHdy5t21E9jerAzSomA5g/GL/IMbA8KszQ5lt4gz/JA=
  on:
    tags: true
    python: '3.5'
  skip_existing: true
